version: '3'

services:
  web:
    build: .
    command: bash -c 'python source/manage.py migrate && python source/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
